
SELECT
DATEPART(YEAR, GETDATE()) AS 'ANO', 
DATEPART(QUARTER,GETDATE() ) AS 'QUARTO DO ANO',
DATEPART(MONTH, GETDATE()) AS 'MÊS',
DATEPART(DAYOFYEAR, GETDATE() ) AS 'DIA DO ANO (DE 1 A 365)',
DATEPART(DAY, GETDATE() ) AS 'DIA',
DATEPART(WEEK, GETDATE() ) AS 'SEMANA',
DATEPART(WEEKDAY, GETDATE() ) AS 'DIA SEMANA',
DATEPART(HOUR, GETDATE() ) AS 'HORA',
DATEPART(MINUTE, GETDATE() ) AS 'MINUTO',
DATEPART(SECOND, GETDATE() ) AS 'SEGUNDO',
DATEPART(MILLISECOND, GETDATE() ) AS 'MILESEGUNDO',
DATEPART(MICROSECOND, GETDATE() ) AS 'MICROSEGUNDO',
DATEPART(NANOSECOND, GETDATE() ) AS 'NANOSEGUNDO'


-- DATEDIFF

SELECT
DATEDIFF(YEAR,'2018-01-01', GETDATE()) AS 'ANO',
DATEDIFF(MONTH,'2018-01-01', GETDATE()) AS 'MÊS',
DATEDIFF(DAY,'2018-01-01', GETDATE()) AS 'DIA',
DATEDIFF(WEEK,'2018-01-01', GETDATE()) AS 'SEMANA',
DATEDIFF(HOUR,'2018-01-01', GETDATE()) AS 'HORA',
DATEDIFF(MINUTE,'2018-01-01', GETDATE()) AS 'MINUTO'


--DATEADO

SELECT
DATEADD(YEAR, 5, GETDATE() ) AS 'ANO ADICIONADO',
DATEADD(YEAR, -5, GETDATE() ) AS 'ANO SUBTRAIDO',
DATEADD(MONTH, 5, GETDATE() ) AS 'MÊS',
DATEADD(DAY, 5, GETDATE() ) AS 'DIA',
DATEADD(WEEK, 5, GETDATE() ) AS 'SEMANA',
DATEADD(HOUR, 5, GETDATE() ) AS 'HORA'



--DATENAME

SELECT
DATENAME(YEAR,GETDATE()) AS 'ANO',
DATENAME(MONTH,GETDATE()) AS 'MÊS',
DATENAME(WEEKDAY,GETDATE()) AS 'DIA DA SEMANA'



-- YEAR, MONTH, DAY, EOMONTH

SELECT 
GETDATE() DATA_SISTEMA,
YEAR(GETDATE() ) AS 'ANO',
MONTH(GETDATE() ) AS 'MÊS',
DAY(GETDATE() ) AS 'DIA',
EOMONTH(GETDATE()) AS 'UTIMO DIA DO MES'

-- ISDATE

SELECT ISDATE(GETDATE()) AS TEST_DATE_VALID

SELECT ISDATE('2018-13-01') AS TEST_DATE_INVALID




-- TRATAMENTO DE NULOS

SELECT
ISNULL(NULL, 'SQL') AS TEST_ISNULL,
NULLIF('SQL', 'SQL') AS TEST_NULLIF,
NULLIF('R-SQL','SQL') AS TEST_NULLIF2,
COALESCE(NULL, NULL, 'SQL') AS TEST_COALESE,
COALESCE(NULL, 'T-SQL', 'SQL') AS TEST_COALECE2 