CREATE DATABASE BD_CONSTRAINTS

USE BD_CONSTRAINTS;


-- IDENTITY

CREATE TABLE tb_identity(
Cod INT IDENTITY PRIMARY KEY,
NOME VARCHAR(50)
)


INSERT INTO tb_identity (NOME)
VALUES ('LINHA1'), ('LINHA2')

-- APRESENTAR ERRO 
INSERT INTO tb_Identity (Cod_NOME)
VALUES (3, 'LINHA', 3)

SELECT * FROM tb_identity

-- PK

CREATE TABLE tb_pk (
Cod INT CONSTRAINT pk_test PRIMARY KEY,
Nome VARCHAR(50)
)

INSERT INTO tb_pk (Cod,NOME)
VALUES (1, 'LINHA 1'), (2,'LINHA 3')

-- APRESENTAR ERRO

-- INSERT INTO tb_pk (Cod,NOME)
-- VALUE (2, 'LINHA 4')


SELECT * FROM tb_pk

-- FK --

CREATE TABLE tb_fk_marca (
Cod INT PRIMARY KEY IDENTITY,
Nome VARCHAR(50)
)

CREATE TABLE tb_fk_carro(
Placa VARCHAR(6) PRIMARY KEY,
modelo VARCHAR(50),
fk_marca INT FOREIGN KEY REFERENCES tb_fk_marca(Cod)
)

INSERT INTO tb_fk_marca (NOME)
VALUES ('PLA001', 'FOX', 1)
		,('PLA002', 'ONIX SEDAN', 2)

-- APRESENTAR ERRO 
INSERT INTO tb_fk_marca (Placa,modelo,fk_marca)
VALUES ('PLA004', 'ARGO', 4)

SELECT * FROM tb_fk_marca
SELECT * FROM tb_fk_carro

-- UNIQUE--

CREATE TABLE tb_unique(
Cod INT PRIMARY KEY IDENTITY,
Nome VARCHAR(50),
CPF CHAR (11) CONSTRAINT UQ_CPF UNIQUE
)

INSERT INTO tb_unique (NOME, CPF)
VALUES ('ESSOA_A', '11245242111'), ('PESSOA_B', '11122233345')

-- APRESENTAR ERRO --

INSERT INTO tb_unique (NOME, CPF)
VALUES ('PESSOA_C', '11122223334')

SELECT * FROM tb_unique


-- NOT NULL--

CREATE TABLE tb_notnull(
Cod INT PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
DT DATE NULL
)

INSERT INTO tb_notnull (NOME, DT)
VALUES ('A', GETDATE()
)

-- APRESENTAR ERRO
INSERT INTO tb_notnull (NOME,DT)
VALUES (NULL, GETDATE()
)

SELECT * FROM tb_notnull

-- DEFAULT--

CREATE TABLE tb_deafult(
Cod int PRIMARY KEY IDENTITY,
Nome VARCHAR (50),
dtinsert DATE CONSTRAINT DF_DATA DEFAULT(GETDATE())
)

INSERT INTO tb_deafult (NOME, dtInsert)
VALUES ('A', '2020-04-15')

-- VERIFICARVALOR DEFAULT
INSERT INTO tb_deafult (NOME)
VALUES('B')

SELECT * FROM tb_deafult


-- CHECK--
CREATE TABLE tb_check(
Cod int PRIMARY KEY IDENTITY,
Nome VARCHAR (50) NOT NULL,
VALOR NUMERIC (6,2) CHECK (VALOR >0 ),
LETRA CHAR(1) CHECK (LETRA IN ('A', 'B', 'C'))
)


INSERT INTO tb_check (NOME, VALOR, LETRA)
VALUES('linha 1', 100.99, 'A')

-- APRESENTAR ERRO 1: CAMPLO VALOR

INSERT INTO tb_check (NOME, VALOR, LETRA)
VALUES ('linha 2', 0, 'A')

-- APRESENTAERRO 2 : CAMPO LETRA

INSERT INTO tb_check (Nome, VALOR, LETRA)
values ('LINHA 2', 20, 'D')

SELECT * FROM tb_check